In [61]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [62]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [63]:
iris = load_iris()

In [64]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [65]:
x = iris.data
y = iris.target

In [66]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [67]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [68]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [69]:
model = KNeighborsClassifier()

In [70]:
model.fit(x_train, y_train)

KNeighborsClassifier()

In [71]:
predict = model.predict(x_test)

In [72]:
predict

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [74]:
cm = confusion_matrix(y_test, predict)

In [75]:
cm

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])

In [76]:
accuracy = accuracy_score(y_test, predict)
print(accuracy)

0.9777777777777777


In [77]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x, y)

KNeighborsClassifier(n_neighbors=3)

In [78]:
sepal_length = float(input("Enter the sepal length:"))
sepal_width = float(input("Enter the sepal_width:"))
petal_length = float(input("Enter the petal length:"))
petal_width = float(input("Enter the petal width:"))

new_data = [[sepal_length, sepal_width, petal_length, petal_width]]

prediction = knn.predict(new_data)
species = iris.target_names[prediction]
print(f"the Predicted Species for the Given value of {sepal_length} is {species}")

Enter the sepal length: 10
Enter the sepal_width: 20
Enter the petal length: 30
Enter the petal width: 40


the Predicted Species for the Given value of 10.0 is ['virginica']


# Now we use SVM model

In [79]:
from sklearn.svm import SVC

In [80]:
model_svc = SVC()

In [81]:
model_svc.fit(x_train, y_train)

SVC()

In [82]:
predict = model_svc.predict(x_test)

In [83]:
cm = confusion_matrix(y_test, predict)

In [84]:
cm

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])

In [85]:
accuracy = accuracy_score(y_test, predict)
print(accuracy)

0.9777777777777777


In [86]:
model_svc.score(x_test, y_test)

0.9777777777777777

In [87]:
pal_length = float(input("Enter the sepal length:"))
sepal_width = float(input("Enter the sepal_width:"))
petal_length = float(input("Enter the petal length:"))
petal_width = float(input("Enter the petal width:"))

new_data = [[sepal_length, sepal_width, petal_length, petal_width]]

prediction = model_svc.predict(new_data)
species = iris.target_names[prediction]
print(f"the Predicted Species for the Given value of {sepal_length} is {species}")

Enter the sepal length: 1
Enter the sepal_width: 1
Enter the petal length: 1
Enter the petal width: 1


the Predicted Species for the Given value of 10.0 is ['setosa']
