# Name = Aseem Athale
# Roll no. = AM37
# Prn = 2122000421

In [1]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

#Question 1


# Create a NumPy array from your data
data = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0],
    [2.3, 2.7],
    [2.0, 1.6],
    [1.0, 1.1],
    [1.5, 1.6],
    [1.1, 0.9]
])

# Standardize the data
scaler = StandardScaler()
data_std = scaler.fit_transform(data)

# Create a PCA object and fit it to the standardized data
pca = PCA()
pca.fit(data_std)

# Get the eigenvalues and eigenvectors
eigenvalues = pca.explained_variance_
eigenvectors = pca.components_

# Print the eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

# You can also get the transformed data (data projected onto the principal components)
data_pca = pca.transform(data_std)
print("\nTransformed Data (PCA):")
print(data_pca)


Eigenvalues:
[2.13992141 0.08230081]

Eigenvectors:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Transformed Data (PCA):
[[-1.08643242 -0.22352364]
 [ 2.3089372   0.17808082]
 [-1.24191895  0.501509  ]
 [-0.34078247  0.16991864]
 [-2.18429003 -0.26475825]
 [-1.16073946  0.23048082]
 [ 0.09260467 -0.45331721]
 [ 1.48210777  0.05566672]
 [ 0.56722643  0.02130455]
 [ 1.56328726 -0.21536146]]


In [2]:
#Question 2

# Create a NumPy array from your data
data1 = np.array([
    [2,4],
    [1,3],
    [0,1],
    [-1,0.5]
])

# Standardize the data
scaler1 = StandardScaler()
data_std1 = scaler.fit_transform(data1)

# Create a PCA object and fit it to the standardized data
pca1 = PCA()
pca1.fit(data_std1)

# Get the eigenvalues and eigenvectors
eigenvalues1 = pca1.explained_variance_
eigenvectors1 = pca1.components_

# Print the eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues1)
print("\nEigenvectors:")
print(eigenvectors1)

# You can also get the transformed data (data projected onto the principal components)
data_pca1 = pca1.transform(data_std1)
print("\nTransformed Data (PCA):")
print(data_pca1)


Eigenvalues:
[2.63577444 0.03089222]

Eigenvectors:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Transformed Data (PCA):
[[ 1.87538639  0.0219802 ]
 [ 0.74868921 -0.11623368]
 [-0.87224962  0.23979409]
 [-1.75182598 -0.14554062]]
